# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName("settingsDialog")
        settingsDialog.resize(600, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(settingsDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.deckCombo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.deckCombo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.deckCombo.setObjectName("deckCombo")
        self.gridLayout.addWidget(self.deckCombo, 2, 2, 1, 1)
        self.fieldsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.fieldsLabel.setObjectName("fieldsLabel")
        self.gridLayout.addWidget(self.fieldsLabel, 1, 4, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 5, 1, 1)
        self.modelCombo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.modelCombo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.modelCombo.setObjectName("modelCombo")
        self.gridLayout.addWidget(self.modelCombo, 3, 2, 1, 1)
        self.provInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.provInput.setMaximumSize(QtCore.QSize(200, 16777215))
        self.provInput.setText("")
        self.provInput.setObjectName("provInput")
        self.gridLayout.addWidget(self.provInput, 1, 2, 1, 1)
        self.fieldMapGrid = QtWidgets.QGridLayout()
        self.fieldMapGrid.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.fieldMapGrid.setContentsMargins(6, -1, 6, -1)
        self.fieldMapGrid.setSpacing(6)
        self.fieldMapGrid.setObjectName("fieldMapGrid")
        self.gridLayout.addLayout(self.fieldMapGrid, 1, 5, 5, 1)
        self.dirLayout = QtWidgets.QHBoxLayout()
        self.dirLayout.setObjectName("dirLayout")
        self.dirInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.dirInput.setEnabled(True)
        self.dirInput.setReadOnly(True)
        self.dirInput.setObjectName("dirInput")
        self.dirLayout.addWidget(self.dirInput)
        self.dirButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.dirButton.setObjectName("dirButton")
        self.dirLayout.addWidget(self.dirButton)
        self.gridLayout.addLayout(self.dirLayout, 0, 2, 1, 4)
        self.tagsInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tagsInput.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tagsInput.setObjectName("tagsInput")
        self.gridLayout.addWidget(self.tagsInput, 4, 2, 1, 1)
        self.provLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.provLabel.setObjectName("provLabel")
        self.gridLayout.addWidget(self.provLabel, 1, 1, 1, 1)
        self.dirLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dirLabel.setObjectName("dirLabel")
        self.gridLayout.addWidget(self.dirLabel, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 3, 7, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 5, 1, 1)
        self.deckLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.deckLabel.setObjectName("deckLabel")
        self.gridLayout.addWidget(self.deckLabel, 2, 1, 1, 1)
        self.modelLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.modelLabel.setObjectName("modelLabel")
        self.gridLayout.addWidget(self.modelLabel, 3, 1, 1, 1)
        self.tagsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.tagsLabel.setObjectName("tagsLabel")
        self.gridLayout.addWidget(self.tagsLabel, 4, 1, 1, 1)
        self.helpLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.helpLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.helpLabel.setIndent(20)
        self.helpLabel.setOpenExternalLinks(True)
        self.helpLabel.setObjectName("helpLabel")
        self.gridLayout.addWidget(self.helpLabel, 5, 1, 2, 2)

        self.retranslateUi(settingsDialog)
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        _translate = QtCore.QCoreApplication.translate
        settingsDialog.setWindowTitle(_translate("settingsDialog", "lines2anki: Lines Import..."))
        self.fieldsLabel.setText(_translate("settingsDialog", "Fields Map"))
        self.dirButton.setText(_translate("settingsDialog", "Browse"))
        self.provLabel.setText(_translate("settingsDialog", "Provenance"))
        self.dirLabel.setText(_translate("settingsDialog", "Directory"))
        self.deckLabel.setText(_translate("settingsDialog", "Deck"))
        self.modelLabel.setText(_translate("settingsDialog", "Note Type"))
        self.tagsLabel.setText(_translate("settingsDialog", "Tags"))
        self.helpLabel.setText(_translate("settingsDialog", "Help text."))
